name: "Hello Actions"
description: "Meet Someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Whom to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
